### ISSUE TITLE
npm install error : 依赖的包（mongoose-paginate.git）不存在

### ISSUE THREAD

**Issue by qingfeng777** [surmon-china/nodepress#11]
npm install error : 依赖的包（ssh://github.com/surmon-china/mongoose-paginate.git）不存在

```
i@mingbai:~/node/nodepress$ npm install
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/surmon-china/mongoose-paginate.git
npm ERR! 
npm ERR! Permission denied (publickey).
npm ERR! fatal: 无法读取远程仓库。
npm ERR! 
npm ERR! 请确认您有正确的访问权限并且仓库存在。
npm ERR! 
npm ERR! exited with error code: 128
```

我查看了相应的git地址，好像没有这个项目。换成其他开源的同名项目，并且把ssh 协议改为http，可以正常运行，但是不知道这么改是否合适，也不太明白为什么会有ssh的依赖，故有此一问。

**Comment by surmon-china** [comment]
因为这个包作者很久没有更新了，有个小 bug，修复后就暂时放在自己项目里，作者不维护所以也没法提 Issues，但这个项目不是私有的，理论上都应该可以访问，你单纯把链接改为 HTTPS 试试，如果可行，我会更新一下

https://github.com/surmon-china/mongoose-paginate

**Comment by qingfengming** [comment]
试了一下，可以

**Comment by surmon-china** [comment]
我找了相关的解决方案，目前没有把  dependencies 依赖项依赖 https 地址的，所以我暂时没有做修改。

**Comment by surmon-china** [comment]
我找了相关的解决方案，目前没有把  dependencies 依赖项依赖 https 地址的，所以我暂时没有做修改。

**Comment by phper-qiu** [comment]
ssh://git@github.com:surmon-china/mongoose-paginate.git
改为
https://github.com/surmon-china/mongoose-paginate
成功

**Comment by surmon-china** [comment]
已更替

**Comment by wojiaoerdandan** [comment]
Could not resolve dependency:
npm ERR! peer passport@"^0.4.0" from @nestjs/passport@8.0.1
npm ERR! node_modules/@nestjs/passport
npm ERR!   @nestjs/passport@"^8.0.1" from the root project
这个包下载不下来呢怎么一直

**Comment by surmon-china** [comment]
> Could not resolve dependency: npm ERR! peer passport@"^0.4.0" from @nestjs/passport@8.0.1 npm ERR! node_modules/@nestjs/passport npm ERR! @nestjs/passport@"^8.0.1" from the root project 这个包下载不下来呢怎么一直

`passport` 是 `@nestjs/passport` 的 `peerDependencies`，`passport` 同时在 `NodePress` 项目中被 [显式依赖](https://github.com/surmon-china/nodepress/blob/main/package.json#L67)；

我在本地分别移除 `node_modules` 及 `yarn.lock` 重装均安装成功，未复现问题，所以你还有其他信息可以提供吗？

**Comment by surmon-china** [comment]
最新做法是，我将逻辑并不算多的 `mongoose-paginate` 的代码进行了优化升级，直接放在了项目内置的 [`utils/paginate`](https://github.com/surmon-china/nodepress/blob/main/src/utils/paginate.ts)。
