### ISSUE TITLE
百度seo 报错400 over quota

### ISSUE THREAD

**Issue by shenxiang11** [surmon-china/nodepress#12]
你好,自己的应用借鉴了你的很多代码,在做百度seo时,推送是成功的,而更新和删除是失败的,请问您是否有这方面的经验
<img width="570" alt="2018-11-15 3 07 12" src="https://user-images.githubusercontent.com/17292115/48535996-28d67480-e8e8-11e8-8f62-ad7fb14b8001.png">

感谢您的开源

**Comment by surmon-china** [comment]
测试地址会失效

**Comment by shenxiang11** [comment]
不是很明白

**Comment by surmon-china** [comment]
1. 截图截大图圈小图
2. 描述问题，着重描述上下文，比如你删报400的文章，是不是已经删过一次了，比如你在什么样的环境下，地址是测试地址还是线上域名地址

先做一名合格的问题提问者
