### ISSUE TITLE
三个博客项目怎么跑起来？

### ISSUE THREAD

**Issue by xiaoming0827** [surmon-china/nodepress#25]
作者您好，看到您关于博客的三个开源项目：前端、后端、后端管理这三个项目，想搭建跑起来学习一下，请问这三个项目怎么一起跑起来呢？比如nodepress这个项目，这个项目对应的数据我该如何建表或者库，有没有直接的sql可以使用？非常感谢

**Comment by surmon-china** [comment]
nodepress 需要 mongodb 和 redis，mongodb 无需建表，只需确认两个数据库都正常运行在本地即可，我会把这点更新到文档中。

至于项目怎么跑，应该你自己去学习，他们本质都是有配套文档的程序而已，并没有什么不对称的信息需要我额外说明的。

**Comment by yemingxingkong** [comment]
可能大佬的世界，和我这种菜鸟的世界不一样吧，数据库链接找不到，安装也报错，我还是慢慢研究研究解决。菜才是原罪，唉！

**Comment by surmon-china** [comment]
@yemingxingkong 良好成熟的方法论是解决问题的良药。
