### ISSUE TITLE
如何实现拦截器依赖注入？

### ISSUE THREAD

**Issue by kakaxiu** [surmon-china/nodepress#34]
我有一个需求， 想判断如果用户jwt满足刷新条件（比如生成超过1天且未过期）就在接口返回中返回一个新的token。
我能想到的做法是建立一个拦截器，判断并为返回结果加上新token。 可是拦截器似乎不支持依赖注入，就没法获得必须的模块（缓存和用户服务）。
有什么好建议么😯

**Comment by kakaxiu** [comment]
也尝试过pipe，但是middleware执行在guard之前，创建新token会导致验证失败。 必须在验证成功以后的操作中进行😯

**Comment by kakaxiu** [comment]
想了半天，大概只能搞一个helper，在控制器里对结果进行处理了😯

**Comment by surmon-china** [comment]
@kakaxiu 
我不太确定交换 Token 是否是一个常规合理做法，但如果 JWT Token 是以 cookie 的形式来续期，这件事就变得很自然了。

如果用 Token 来实现，我建议的实现思路是：
服务端提供一个类似 “更新 Token” 的接口，假设叫 renewal 吧，它接受一个旧的有效的 Token，只要 Token 有效，就返回一个即刻生成的新 Token；而 “维护 Token 更新周期” 这件事严格来说只应该客户端去关心，也只有客户端有条件知道并做到何时更新 Token，客户端可以判断（时间周期性或事件周期性）Token 是否快过期，从而决定是否要换最新的 Token。

**Comment by kakaxiu** [comment]
有道理，我可能被之前的一些问题束缚了思路😯
