### ISSUE TITLE
yarn start:prod出现以下报错

### ISSUE THREAD

**Issue by Vanvi-Chan** [surmon-china/nodepress#68]
[error] [nodepress] (node:88584) UnhandledPromiseRejectionWarning: Error: ENOENT: n
o such file or directory, open 'E:\Study\surmon.me\public\sitemap.xml'
    at Object.openSync (fs.js:457:3)
    at Object.writeFileSync (fs.js:1282:35)
    at E:\Study\nodepress-master\dist\modules\syndication\syndication.service.js:192
:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
 [error] [nodepress] (node:88584) UnhandledPromiseRejectionWarning: Unhandled promis
e rejection. This error originated either by throwing inside of an async function wi
thout a catch block, or by rejecting a promise which was not handled with .catch().
To terminate the node process on unhandled promise rejection, use the CLI flag `--un
handled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_reject
ions_mode). (rejection id: 1)
 [error] [nodepress] (node:88584) [DEP0018] DeprecationWarning: Unhandled promise re
jections are deprecated. In the future, promise rejections that are not handled will
 terminate the Node.js process with a non-zero exit code.
 [warn] [nodepress] 邮件客户端初始化连接失败！将在半小时后重试： Invalid login: 535
Login Fail. Please enter your authorization code to login. More information in http:
//service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
 [warn] [nodepress] Akismet 验证失败！无法工作，原因： Akismet Key 无效！

该如何解决呢？

**Comment by surmon-china** [comment]
最新的版本更新就不存在这个错误了，因为 [移除了 `syndication ` 模块](https://github.com/surmon-china/nodepress/blob/main/CHANGELOG.md#v360-2021-12-06)，不存在文件 IO 行为了。
