### ISSUE TITLE
npm run dev  好像并没有运行启动程序

### ISSUE THREAD

**Issue by liweiyuVIE** [surmon-china/nodepress#8]
`D:\web\nodepress-master>cnpm run dev

> NodePress@1.0.0 dev D:\web\nodepress-master
> nodemon --exec "set NODE_ENV=development node --harmony

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `set NODE_ENV=development node --harmo
[nodemon] clean exit - waiting for changes before restart`

这样是正常的吗？ 我用的是WINDOW 。请指点

**Comment by surmon-china** [comment]
有什么错误，什么异常，什么输出？

**Comment by liweiyuVIE** [comment]
安装时也有错误：
![image](https://user-images.githubusercontent.com/20943221/30042998-9ac65682-9227-11e7-80f2-d2d86f403ad2.png)

我是在WINDOWS操作的。

**Comment by surmon-china** [comment]
所以你能看明白这黑底白字的的错误告诉你缺少什么吗

**Comment by liweiyuVIE** [comment]
python ?  node-gyp ?

**Comment by liweiyuVIE** [comment]
安装了Pyrthon 2..7 和VS2005后，运行出现这样



![qq 20170905134643](https://user-images.githubusercontent.com/20943221/30046929-cfde6300-9240-11e7-91b7-6ae4fb87cbb9.png)

麻烦大神指点下？有点懵了。

**Comment by surmon-china** [comment]
此问题已过时，相关包已不被使用，已废弃。
