### ISSUE TITLE
可以考虑加入 swagger

### ISSUE THREAD

**Issue by hahacium** [surmon-china/nodepress#89]
加入 swagger 接口展示和调试都可以方便直观很多

**Comment by surmon-china** [comment]
没有用 Swagger，但是生成了[一套文档](https://github.surmon.me/nodepress/)。

**Comment by qraxiss** [comment]
I cant reach the api documentation

<img width="618" alt="image" src="https://github.com/surmon-china/nodepress/assets/92579832/eb591485-548c-450c-b090-73f2d7a2a069">
