### ISSUE TITLE
请问能出一个简易教程吗？

### ISSUE THREAD

**Issue by YYQ8023** [surmon-china/nodepress#9]
感谢作者大大的付出，谢谢。
本人目前主要从事前端方面的工作，但是对后端也**很感兴趣**，前段时间仔细看了看egg.js和koa这些框架，但是没怎么整明白，一些helloworld可以跑起来，但是像大佬这种就不行了，所以希望大佬出一个**简易教程**，我想先让它跑起来，然后再仔细琢磨。
万分感谢。

**Comment by surmon-china** [comment]
可是，真的已经，很简单了。
